#pragma once
/**
 * ============================================================
 *  InstantIoTWhen.hpp — Per-widget declarative macros
 * ============================================================
 *
 * Shorthand syntax for writing per-widget-id handlers:
 *
 *   ISimpleButton("btn1") {
 *       WHEN_TOGGLED(isOn) { analogWrite(LED_PIN, isOn ? 255 : 0); }
 *       WHEN_PRESSED       { Serial.println("press"); }
 *       WHEN_LONG_PRESSED  { Serial.println("hold"); }
 *       WHEN_RELEASED      { Serial.println("release"); }
 *   };
 *
 *   IAdvancedButton("action1") {
 *       WHEN_TOGGLED(on) { digitalWrite(RELAY_PIN, on); }
 *   };
 *
 *   IJoystick("joy1") {
 *       WHEN_MOVED(x, y) { driveMotors((int)(y * 2.55f), (int)(x * 2.55f)); }
 *       WHEN_RELEASED    { driveMotors(0, 0); }
 *   };
 *
 * ## Multi-instance
 *
 * Multiple blocks of the same widget type with distinct ids
 * coexist:
 *
 *   ISimpleButton("btn1") { ... };
 *   ISimpleButton("btn2") { ... };
 *
 * Each block registers its own handler in an intrusive linked list
 * (12 B RAM per block on ESP32). Dispatch: 1 strcmp
 * per handler registered for the relevant type.
 *
 * ## Legacy coexistence
 *
 * `void onSimpleButtonEvent(const SimpleButtonEvent&)` etc.
 * still work: both paths are called. You can
 * migrate sketch by sketch without breakage.
 *
 * ## Mandatory trailing ;
 *
 * The block closes with `};` — the `;` terminates the
 * `static auto _reg = WidgetRegistrar(...)` definition generated by the macro.
 *
 * ============================================================
 */

#include <Arduino.h>
#include "../core/Registry.hpp"
#include "../core/InstantIoTMessage.hpp"

// ============================================================
// 🔧 HELPERS token-pasting
// ============================================================
#ifndef _IIO_CAT
#define _IIO_CAT(a, b)  a##b
#define _IIO_XCAT(a, b) _IIO_CAT(a, b)
#define _IIO_UID(base)  _IIO_XCAT(base, __COUNTER__)
#endif

// ============================================================
// 🎯 I<Widget>(id) — declares a file-scope handler for the id
// ============================================================

#define ISimpleButton(id) _IIO_ISIMPLEBTN_IMPL(id, _IIO_UID(_iioSbF_), _IIO_UID(_iioSbR_))
#define _IIO_ISIMPLEBTN_IMPL(id, FN, REG)                                  \
    static void FN(const InstantIoT::SimpleButtonEvent&);                  \
    static InstantIoT::WidgetRegistrar<InstantIoT::SimpleButtonEvent>      \
        REG(id, &FN);                                                      \
    static void FN(const InstantIoT::SimpleButtonEvent& e)

#define IAdvancedButton(id) _IIO_IADVBTN_IMPL(id, _IIO_UID(_iioAbF_), _IIO_UID(_iioAbR_))
#define _IIO_IADVBTN_IMPL(id, FN, REG)                                     \
    static void FN(const InstantIoT::AdvancedButtonEvent&);                \
    static InstantIoT::WidgetRegistrar<InstantIoT::AdvancedButtonEvent>    \
        REG(id, &FN);                                                      \
    static void FN(const InstantIoT::AdvancedButtonEvent& e)

#define IJoystick(id) _IIO_IJOY_IMPL(id, _IIO_UID(_iioJyF_), _IIO_UID(_iioJyR_))
#define _IIO_IJOY_IMPL(id, FN, REG)                                        \
    static void FN(const InstantIoT::JoystickEvent&);                      \
    static InstantIoT::WidgetRegistrar<InstantIoT::JoystickEvent>          \
        REG(id, &FN);                                                      \
    static void FN(const InstantIoT::JoystickEvent& e)

#define IHorizontalSlider(id) _IIO_IHSL_IMPL(id, _IIO_UID(_iioHsF_), _IIO_UID(_iioHsR_))
#define _IIO_IHSL_IMPL(id, FN, REG)                                        \
    static void FN(const InstantIoT::HorizontalSliderEvent&);              \
    static InstantIoT::WidgetRegistrar<InstantIoT::HorizontalSliderEvent>  \
        REG(id, &FN);                                                      \
    static void FN(const InstantIoT::HorizontalSliderEvent& e)

#define IVerticalSlider(id) _IIO_IVSL_IMPL(id, _IIO_UID(_iioVsF_), _IIO_UID(_iioVsR_))
#define _IIO_IVSL_IMPL(id, FN, REG)                                        \
    static void FN(const InstantIoT::VerticalSliderEvent&);                \
    static InstantIoT::WidgetRegistrar<InstantIoT::VerticalSliderEvent>    \
        REG(id, &FN);                                                      \
    static void FN(const InstantIoT::VerticalSliderEvent& e)

#define ISwitch(id) _IIO_ISW_IMPL(id, _IIO_UID(_iioSwF_), _IIO_UID(_iioSwR_))
#define _IIO_ISW_IMPL(id, FN, REG)                                         \
    static void FN(const InstantIoT::SwitchEvent&);                        \
    static InstantIoT::WidgetRegistrar<InstantIoT::SwitchEvent>            \
        REG(id, &FN);                                                      \
    static void FN(const InstantIoT::SwitchEvent& e)

#define IDirectionPad(id) _IIO_IDP_IMPL(id, _IIO_UID(_iioDpF_), _IIO_UID(_iioDpR_))
#define _IIO_IDP_IMPL(id, FN, REG)                                         \
    static void FN(const InstantIoT::DirectionPadEvent&);                  \
    static InstantIoT::WidgetRegistrar<InstantIoT::DirectionPadEvent>      \
        REG(id, &FN);                                                      \
    static void FN(const InstantIoT::DirectionPadEvent& e)

#define ISegmentedSwitch(id) _IIO_ISEG_IMPL(id, _IIO_UID(_iioSgF_), _IIO_UID(_iioSgR_))
#define _IIO_ISEG_IMPL(id, FN, REG)                                        \
    static void FN(const InstantIoT::SegmentedSwitchEvent&);               \
    static InstantIoT::WidgetRegistrar<InstantIoT::SegmentedSwitchEvent>   \
        REG(id, &FN);                                                      \
    static void FN(const InstantIoT::SegmentedSwitchEvent& e)

#define IEmergencyButton(id) _IIO_IEMB_IMPL(id, _IIO_UID(_iioEmF_), _IIO_UID(_iioEmR_))
#define _IIO_IEMB_IMPL(id, FN, REG)                                        \
    static void FN(const InstantIoT::EmergencyButtonEvent&);               \
    static InstantIoT::WidgetRegistrar<InstantIoT::EmergencyButtonEvent>   \
        REG(id, &FN);                                                      \
    static void FN(const InstantIoT::EmergencyButtonEvent& e)

// ============================================================
// 🧩 Per-type predicates (overloaded) — enable a single
// `WHEN_RELEASED` that works for Button and Joystick
// ============================================================

namespace InstantIoT {

inline bool _whenPressed(const SimpleButtonEvent& e)       { return e.kind == ButtonEventKind::Press; }
inline bool _whenPressed(const AdvancedButtonEvent& e)     { return e.kind == ButtonEventKind::Press; }

inline bool _whenReleased(const SimpleButtonEvent& e)      { return e.kind == ButtonEventKind::Release; }
inline bool _whenReleased(const AdvancedButtonEvent& e)    { return e.kind == ButtonEventKind::Release; }
inline bool _whenReleased(const JoystickEvent& e)          { return e.kind == JoystickEventKind::Released; }

inline bool _whenLongPressed(const SimpleButtonEvent& e)   { return e.kind == ButtonEventKind::LongPress; }
inline bool _whenLongPressed(const AdvancedButtonEvent& e) { return e.kind == ButtonEventKind::LongPress; }

inline bool _whenToggled(const SimpleButtonEvent& e)       { return e.kind == ButtonEventKind::Toggle; }
inline bool _whenToggled(const AdvancedButtonEvent& e)     { return e.kind == ButtonEventKind::Toggle; }
inline bool _whenToggled(const SwitchEvent& e)             { return e.kind == SwitchEventKind::Toggle; }

inline bool _whenMoved(const JoystickEvent& e)             { return e.kind == JoystickEventKind::PositionChanged; }

// ── Switch ───────────────────────────────────────────────
inline bool _whenTurnedOn(const SwitchEvent& e)            { return e.kind == SwitchEventKind::TurnOn; }
inline bool _whenTurnedOff(const SwitchEvent& e)           { return e.kind == SwitchEventKind::TurnOff; }
inline bool _whenSwitchSetValue(const SwitchEvent& e)      { return e.kind == SwitchEventKind::SetValue; }

// ── Slider ───────────────────────────────────────────────
inline bool _whenChanging(const HorizontalSliderEvent& e)  { return e.kind == SliderEventKind::ValueChanging; }
inline bool _whenChanging(const VerticalSliderEvent& e)    { return e.kind == SliderEventKind::ValueChanging; }

inline bool _whenChanged(const HorizontalSliderEvent& e)   { return e.kind == SliderEventKind::ValueChanged; }
inline bool _whenChanged(const VerticalSliderEvent& e)     { return e.kind == SliderEventKind::ValueChanged; }

// ── DirectionPad ─────────────────────────────────────────
inline bool _whenPadPressed(const DirectionPadEvent& e)    { return e.kind == DPadEventKind::Press; }
inline bool _whenPadReleased(const DirectionPadEvent& e)   { return e.kind == DPadEventKind::Release; }
inline bool _whenPadLongPressed(const DirectionPadEvent& e){ return e.kind == DPadEventKind::LongPress; }

// ── SegmentedSwitch ──────────────────────────────────────
inline bool _whenSelectionChanged(const SegmentedSwitchEvent& e) { return e.kind == SegmentedEventKind::SelectionChanged; }
inline bool _whenSegmentSelected(const SegmentedSwitchEvent& e)  { return e.kind == SegmentedEventKind::SegmentSelected; }
inline bool _whenSegmentDeselected(const SegmentedSwitchEvent& e){ return e.kind == SegmentedEventKind::SegmentDeselected; }

// ── EmergencyButton ──────────────────────────────────────
inline bool _whenTriggered(const EmergencyButtonEvent& e)  { return e.kind == EmergencyEventKind::Trigger; }
inline bool _whenReset(const EmergencyButtonEvent& e)      { return e.kind == EmergencyEventKind::Reset; }

} // namespace InstantIoT

// ============================================================
// 🎯 WHEN_* — internal guards inside I<Widget> blocks
//
// `e` is the argument of the function generated by I<Widget>(id).
// Predicates are resolved by overload based on the type of `e`.
// ============================================================

// --- Without capture ----------------------------------------
#define WHEN_PRESSED      if (InstantIoT::_whenPressed(e))
#define WHEN_RELEASED     if (InstantIoT::_whenReleased(e))
#define WHEN_LONG_PRESSED if (InstantIoT::_whenLongPressed(e))

// --- With capture of a bool variable ------------------------
// "if init-statement" idiom (C++17) to have only one if
#define WHEN_TOGGLED(var_isOn)                                                 \
    if (InstantIoT::_whenToggled(e))                                           \
        if (bool var_isOn = e.isOn; true)

// --- With capture of two float variables (joystick) --------
// Two nested if-init (C++17) — each condition is a `true` bool,
// so the user block always runs once if the kind matches.
#define WHEN_MOVED(var_x, var_y)                                               \
    if (InstantIoT::_whenMoved(e))                                             \
        if (float var_x = e.x; true)                                           \
            if (float var_y = e.y; true)

// ============================================================
// 🎚️ SLIDER  (H and V — same DSL)
// ============================================================
// Streaming during drag (ValueChanging) — captures the float value
#define WHEN_CHANGING(var_v)                                                   \
    if (InstantIoT::_whenChanging(e))                                          \
        if (float var_v = e.value; true)

// Final value on release (ValueChanged) — captures the float value
#define WHEN_CHANGED(var_v)                                                    \
    if (InstantIoT::_whenChanged(e))                                           \
        if (float var_v = e.value; true)

// ============================================================
// 🔘 SWITCH
// ============================================================
#define WHEN_TURNED_ON     if (InstantIoT::_whenTurnedOn(e))
#define WHEN_TURNED_OFF    if (InstantIoT::_whenTurnedOff(e))
// WHEN_TOGGLED(isOn) is already defined (overload on SwitchEvent).
// WHEN_SWITCH_SET(isOn) captures e.isOn for events with kind=SetValue.
#define WHEN_SWITCH_SET(var_isOn)                                              \
    if (InstantIoT::_whenSwitchSetValue(e))                                    \
        if (bool var_isOn = e.isOn; true)

// ============================================================
// 🎮 DIRECTION PAD
// ============================================================
// Captures e.button (DPadButton enum) — user inspects with a switch
#define WHEN_PAD_PRESSED(var_btn)                                              \
    if (InstantIoT::_whenPadPressed(e))                                        \
        if (InstantIoT::DPadButton var_btn = e.button; true)

#define WHEN_PAD_RELEASED(var_btn)                                             \
    if (InstantIoT::_whenPadReleased(e))                                       \
        if (InstantIoT::DPadButton var_btn = e.button; true)

#define WHEN_PAD_LONG_PRESSED(var_btn)                                         \
    if (InstantIoT::_whenPadLongPressed(e))                                    \
        if (InstantIoT::DPadButton var_btn = e.button; true)

// ============================================================
// 🔀 SEGMENTED SWITCH
// ============================================================
// Captures selectedIndex (int)
#define WHEN_SELECTION_CHANGED(var_idx)                                        \
    if (InstantIoT::_whenSelectionChanged(e))                                  \
        if (int var_idx = e.selectedIndex; true)

#define WHEN_SEGMENT_SELECTED(var_idx)                                         \
    if (InstantIoT::_whenSegmentSelected(e))                                   \
        if (int var_idx = e.selectedIndex; true)

#define WHEN_SEGMENT_DESELECTED(var_idx)                                       \
    if (InstantIoT::_whenSegmentDeselected(e))                                 \
        if (int var_idx = e.selectedIndex; true)

// ============================================================
// 🚨 EMERGENCY BUTTON
// ============================================================
#define WHEN_TRIGGERED  if (InstantIoT::_whenTriggered(e))
#define WHEN_RESET      if (InstantIoT::_whenReset(e))
